// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: netmon/v1/netmon.proto

package netmonv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/kahoon/netmon/proto/netmon/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NetmonServiceName is the fully-qualified name of the NetmonService service.
	NetmonServiceName = "netmon.v1.NetmonService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NetmonServiceGetStatusProcedure is the fully-qualified name of the NetmonService's GetStatus RPC.
	NetmonServiceGetStatusProcedure = "/netmon.v1.NetmonService/GetStatus"
	// NetmonServiceWatchStatusProcedure is the fully-qualified name of the NetmonService's WatchStatus
	// RPC.
	NetmonServiceWatchStatusProcedure = "/netmon.v1.NetmonService/WatchStatus"
	// NetmonServiceWatchTasksProcedure is the fully-qualified name of the NetmonService's WatchTasks
	// RPC.
	NetmonServiceWatchTasksProcedure = "/netmon.v1.NetmonService/WatchTasks"
	// NetmonServiceTraceProcedure is the fully-qualified name of the NetmonService's Trace RPC.
	NetmonServiceTraceProcedure = "/netmon.v1.NetmonService/Trace"
	// NetmonServiceGetStateProcedure is the fully-qualified name of the NetmonService's GetState RPC.
	NetmonServiceGetStateProcedure = "/netmon.v1.NetmonService/GetState"
	// NetmonServiceGetInfoProcedure is the fully-qualified name of the NetmonService's GetInfo RPC.
	NetmonServiceGetInfoProcedure = "/netmon.v1.NetmonService/GetInfo"
	// NetmonServiceGetStatsProcedure is the fully-qualified name of the NetmonService's GetStats RPC.
	NetmonServiceGetStatsProcedure = "/netmon.v1.NetmonService/GetStats"
	// NetmonServiceRefreshProcedure is the fully-qualified name of the NetmonService's Refresh RPC.
	NetmonServiceRefreshProcedure = "/netmon.v1.NetmonService/Refresh"
	// NetmonServiceSetDebugProcedure is the fully-qualified name of the NetmonService's SetDebug RPC.
	NetmonServiceSetDebugProcedure = "/netmon.v1.NetmonService/SetDebug"
	// NetmonServiceSetRuntimeStatsIntervalProcedure is the fully-qualified name of the NetmonService's
	// SetRuntimeStatsInterval RPC.
	NetmonServiceSetRuntimeStatsIntervalProcedure = "/netmon.v1.NetmonService/SetRuntimeStatsInterval"
)

// NetmonServiceClient is a client for the netmon.v1.NetmonService service.
type NetmonServiceClient interface {
	GetStatus(context.Context, *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error)
	WatchStatus(context.Context, *connect.Request[v1.WatchStatusRequest]) (*connect.ServerStreamForClient[v1.WatchStatusResponse], error)
	WatchTasks(context.Context, *connect.Request[v1.WatchTasksRequest]) (*connect.ServerStreamForClient[v1.WatchTasksResponse], error)
	Trace(context.Context, *connect.Request[v1.TraceRequest]) (*connect.ServerStreamForClient[v1.TraceResponse], error)
	GetState(context.Context, *connect.Request[v1.GetStateRequest]) (*connect.Response[v1.GetStateResponse], error)
	GetInfo(context.Context, *connect.Request[v1.GetInfoRequest]) (*connect.Response[v1.GetInfoResponse], error)
	GetStats(context.Context, *connect.Request[v1.GetStatsRequest]) (*connect.Response[v1.GetStatsResponse], error)
	Refresh(context.Context, *connect.Request[v1.RefreshRequest]) (*connect.Response[v1.RefreshResponse], error)
	SetDebug(context.Context, *connect.Request[v1.SetDebugRequest]) (*connect.Response[v1.SetDebugResponse], error)
	SetRuntimeStatsInterval(context.Context, *connect.Request[v1.SetRuntimeStatsIntervalRequest]) (*connect.Response[v1.SetRuntimeStatsIntervalResponse], error)
}

// NewNetmonServiceClient constructs a client for the netmon.v1.NetmonService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNetmonServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NetmonServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	netmonServiceMethods := v1.File_netmon_v1_netmon_proto.Services().ByName("NetmonService").Methods()
	return &netmonServiceClient{
		getStatus: connect.NewClient[v1.GetStatusRequest, v1.GetStatusResponse](
			httpClient,
			baseURL+NetmonServiceGetStatusProcedure,
			connect.WithSchema(netmonServiceMethods.ByName("GetStatus")),
			connect.WithClientOptions(opts...),
		),
		watchStatus: connect.NewClient[v1.WatchStatusRequest, v1.WatchStatusResponse](
			httpClient,
			baseURL+NetmonServiceWatchStatusProcedure,
			connect.WithSchema(netmonServiceMethods.ByName("WatchStatus")),
			connect.WithClientOptions(opts...),
		),
		watchTasks: connect.NewClient[v1.WatchTasksRequest, v1.WatchTasksResponse](
			httpClient,
			baseURL+NetmonServiceWatchTasksProcedure,
			connect.WithSchema(netmonServiceMethods.ByName("WatchTasks")),
			connect.WithClientOptions(opts...),
		),
		trace: connect.NewClient[v1.TraceRequest, v1.TraceResponse](
			httpClient,
			baseURL+NetmonServiceTraceProcedure,
			connect.WithSchema(netmonServiceMethods.ByName("Trace")),
			connect.WithClientOptions(opts...),
		),
		getState: connect.NewClient[v1.GetStateRequest, v1.GetStateResponse](
			httpClient,
			baseURL+NetmonServiceGetStateProcedure,
			connect.WithSchema(netmonServiceMethods.ByName("GetState")),
			connect.WithClientOptions(opts...),
		),
		getInfo: connect.NewClient[v1.GetInfoRequest, v1.GetInfoResponse](
			httpClient,
			baseURL+NetmonServiceGetInfoProcedure,
			connect.WithSchema(netmonServiceMethods.ByName("GetInfo")),
			connect.WithClientOptions(opts...),
		),
		getStats: connect.NewClient[v1.GetStatsRequest, v1.GetStatsResponse](
			httpClient,
			baseURL+NetmonServiceGetStatsProcedure,
			connect.WithSchema(netmonServiceMethods.ByName("GetStats")),
			connect.WithClientOptions(opts...),
		),
		refresh: connect.NewClient[v1.RefreshRequest, v1.RefreshResponse](
			httpClient,
			baseURL+NetmonServiceRefreshProcedure,
			connect.WithSchema(netmonServiceMethods.ByName("Refresh")),
			connect.WithClientOptions(opts...),
		),
		setDebug: connect.NewClient[v1.SetDebugRequest, v1.SetDebugResponse](
			httpClient,
			baseURL+NetmonServiceSetDebugProcedure,
			connect.WithSchema(netmonServiceMethods.ByName("SetDebug")),
			connect.WithClientOptions(opts...),
		),
		setRuntimeStatsInterval: connect.NewClient[v1.SetRuntimeStatsIntervalRequest, v1.SetRuntimeStatsIntervalResponse](
			httpClient,
			baseURL+NetmonServiceSetRuntimeStatsIntervalProcedure,
			connect.WithSchema(netmonServiceMethods.ByName("SetRuntimeStatsInterval")),
			connect.WithClientOptions(opts...),
		),
	}
}

// netmonServiceClient implements NetmonServiceClient.
type netmonServiceClient struct {
	getStatus               *connect.Client[v1.GetStatusRequest, v1.GetStatusResponse]
	watchStatus             *connect.Client[v1.WatchStatusRequest, v1.WatchStatusResponse]
	watchTasks              *connect.Client[v1.WatchTasksRequest, v1.WatchTasksResponse]
	trace                   *connect.Client[v1.TraceRequest, v1.TraceResponse]
	getState                *connect.Client[v1.GetStateRequest, v1.GetStateResponse]
	getInfo                 *connect.Client[v1.GetInfoRequest, v1.GetInfoResponse]
	getStats                *connect.Client[v1.GetStatsRequest, v1.GetStatsResponse]
	refresh                 *connect.Client[v1.RefreshRequest, v1.RefreshResponse]
	setDebug                *connect.Client[v1.SetDebugRequest, v1.SetDebugResponse]
	setRuntimeStatsInterval *connect.Client[v1.SetRuntimeStatsIntervalRequest, v1.SetRuntimeStatsIntervalResponse]
}

// GetStatus calls netmon.v1.NetmonService.GetStatus.
func (c *netmonServiceClient) GetStatus(ctx context.Context, req *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error) {
	return c.getStatus.CallUnary(ctx, req)
}

// WatchStatus calls netmon.v1.NetmonService.WatchStatus.
func (c *netmonServiceClient) WatchStatus(ctx context.Context, req *connect.Request[v1.WatchStatusRequest]) (*connect.ServerStreamForClient[v1.WatchStatusResponse], error) {
	return c.watchStatus.CallServerStream(ctx, req)
}

// WatchTasks calls netmon.v1.NetmonService.WatchTasks.
func (c *netmonServiceClient) WatchTasks(ctx context.Context, req *connect.Request[v1.WatchTasksRequest]) (*connect.ServerStreamForClient[v1.WatchTasksResponse], error) {
	return c.watchTasks.CallServerStream(ctx, req)
}

// Trace calls netmon.v1.NetmonService.Trace.
func (c *netmonServiceClient) Trace(ctx context.Context, req *connect.Request[v1.TraceRequest]) (*connect.ServerStreamForClient[v1.TraceResponse], error) {
	return c.trace.CallServerStream(ctx, req)
}

// GetState calls netmon.v1.NetmonService.GetState.
func (c *netmonServiceClient) GetState(ctx context.Context, req *connect.Request[v1.GetStateRequest]) (*connect.Response[v1.GetStateResponse], error) {
	return c.getState.CallUnary(ctx, req)
}

// GetInfo calls netmon.v1.NetmonService.GetInfo.
func (c *netmonServiceClient) GetInfo(ctx context.Context, req *connect.Request[v1.GetInfoRequest]) (*connect.Response[v1.GetInfoResponse], error) {
	return c.getInfo.CallUnary(ctx, req)
}

// GetStats calls netmon.v1.NetmonService.GetStats.
func (c *netmonServiceClient) GetStats(ctx context.Context, req *connect.Request[v1.GetStatsRequest]) (*connect.Response[v1.GetStatsResponse], error) {
	return c.getStats.CallUnary(ctx, req)
}

// Refresh calls netmon.v1.NetmonService.Refresh.
func (c *netmonServiceClient) Refresh(ctx context.Context, req *connect.Request[v1.RefreshRequest]) (*connect.Response[v1.RefreshResponse], error) {
	return c.refresh.CallUnary(ctx, req)
}

// SetDebug calls netmon.v1.NetmonService.SetDebug.
func (c *netmonServiceClient) SetDebug(ctx context.Context, req *connect.Request[v1.SetDebugRequest]) (*connect.Response[v1.SetDebugResponse], error) {
	return c.setDebug.CallUnary(ctx, req)
}

// SetRuntimeStatsInterval calls netmon.v1.NetmonService.SetRuntimeStatsInterval.
func (c *netmonServiceClient) SetRuntimeStatsInterval(ctx context.Context, req *connect.Request[v1.SetRuntimeStatsIntervalRequest]) (*connect.Response[v1.SetRuntimeStatsIntervalResponse], error) {
	return c.setRuntimeStatsInterval.CallUnary(ctx, req)
}

// NetmonServiceHandler is an implementation of the netmon.v1.NetmonService service.
type NetmonServiceHandler interface {
	GetStatus(context.Context, *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error)
	WatchStatus(context.Context, *connect.Request[v1.WatchStatusRequest], *connect.ServerStream[v1.WatchStatusResponse]) error
	WatchTasks(context.Context, *connect.Request[v1.WatchTasksRequest], *connect.ServerStream[v1.WatchTasksResponse]) error
	Trace(context.Context, *connect.Request[v1.TraceRequest], *connect.ServerStream[v1.TraceResponse]) error
	GetState(context.Context, *connect.Request[v1.GetStateRequest]) (*connect.Response[v1.GetStateResponse], error)
	GetInfo(context.Context, *connect.Request[v1.GetInfoRequest]) (*connect.Response[v1.GetInfoResponse], error)
	GetStats(context.Context, *connect.Request[v1.GetStatsRequest]) (*connect.Response[v1.GetStatsResponse], error)
	Refresh(context.Context, *connect.Request[v1.RefreshRequest]) (*connect.Response[v1.RefreshResponse], error)
	SetDebug(context.Context, *connect.Request[v1.SetDebugRequest]) (*connect.Response[v1.SetDebugResponse], error)
	SetRuntimeStatsInterval(context.Context, *connect.Request[v1.SetRuntimeStatsIntervalRequest]) (*connect.Response[v1.SetRuntimeStatsIntervalResponse], error)
}

// NewNetmonServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNetmonServiceHandler(svc NetmonServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	netmonServiceMethods := v1.File_netmon_v1_netmon_proto.Services().ByName("NetmonService").Methods()
	netmonServiceGetStatusHandler := connect.NewUnaryHandler(
		NetmonServiceGetStatusProcedure,
		svc.GetStatus,
		connect.WithSchema(netmonServiceMethods.ByName("GetStatus")),
		connect.WithHandlerOptions(opts...),
	)
	netmonServiceWatchStatusHandler := connect.NewServerStreamHandler(
		NetmonServiceWatchStatusProcedure,
		svc.WatchStatus,
		connect.WithSchema(netmonServiceMethods.ByName("WatchStatus")),
		connect.WithHandlerOptions(opts...),
	)
	netmonServiceWatchTasksHandler := connect.NewServerStreamHandler(
		NetmonServiceWatchTasksProcedure,
		svc.WatchTasks,
		connect.WithSchema(netmonServiceMethods.ByName("WatchTasks")),
		connect.WithHandlerOptions(opts...),
	)
	netmonServiceTraceHandler := connect.NewServerStreamHandler(
		NetmonServiceTraceProcedure,
		svc.Trace,
		connect.WithSchema(netmonServiceMethods.ByName("Trace")),
		connect.WithHandlerOptions(opts...),
	)
	netmonServiceGetStateHandler := connect.NewUnaryHandler(
		NetmonServiceGetStateProcedure,
		svc.GetState,
		connect.WithSchema(netmonServiceMethods.ByName("GetState")),
		connect.WithHandlerOptions(opts...),
	)
	netmonServiceGetInfoHandler := connect.NewUnaryHandler(
		NetmonServiceGetInfoProcedure,
		svc.GetInfo,
		connect.WithSchema(netmonServiceMethods.ByName("GetInfo")),
		connect.WithHandlerOptions(opts...),
	)
	netmonServiceGetStatsHandler := connect.NewUnaryHandler(
		NetmonServiceGetStatsProcedure,
		svc.GetStats,
		connect.WithSchema(netmonServiceMethods.ByName("GetStats")),
		connect.WithHandlerOptions(opts...),
	)
	netmonServiceRefreshHandler := connect.NewUnaryHandler(
		NetmonServiceRefreshProcedure,
		svc.Refresh,
		connect.WithSchema(netmonServiceMethods.ByName("Refresh")),
		connect.WithHandlerOptions(opts...),
	)
	netmonServiceSetDebugHandler := connect.NewUnaryHandler(
		NetmonServiceSetDebugProcedure,
		svc.SetDebug,
		connect.WithSchema(netmonServiceMethods.ByName("SetDebug")),
		connect.WithHandlerOptions(opts...),
	)
	netmonServiceSetRuntimeStatsIntervalHandler := connect.NewUnaryHandler(
		NetmonServiceSetRuntimeStatsIntervalProcedure,
		svc.SetRuntimeStatsInterval,
		connect.WithSchema(netmonServiceMethods.ByName("SetRuntimeStatsInterval")),
		connect.WithHandlerOptions(opts...),
	)
	return "/netmon.v1.NetmonService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NetmonServiceGetStatusProcedure:
			netmonServiceGetStatusHandler.ServeHTTP(w, r)
		case NetmonServiceWatchStatusProcedure:
			netmonServiceWatchStatusHandler.ServeHTTP(w, r)
		case NetmonServiceWatchTasksProcedure:
			netmonServiceWatchTasksHandler.ServeHTTP(w, r)
		case NetmonServiceTraceProcedure:
			netmonServiceTraceHandler.ServeHTTP(w, r)
		case NetmonServiceGetStateProcedure:
			netmonServiceGetStateHandler.ServeHTTP(w, r)
		case NetmonServiceGetInfoProcedure:
			netmonServiceGetInfoHandler.ServeHTTP(w, r)
		case NetmonServiceGetStatsProcedure:
			netmonServiceGetStatsHandler.ServeHTTP(w, r)
		case NetmonServiceRefreshProcedure:
			netmonServiceRefreshHandler.ServeHTTP(w, r)
		case NetmonServiceSetDebugProcedure:
			netmonServiceSetDebugHandler.ServeHTTP(w, r)
		case NetmonServiceSetRuntimeStatsIntervalProcedure:
			netmonServiceSetRuntimeStatsIntervalHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNetmonServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNetmonServiceHandler struct{}

func (UnimplementedNetmonServiceHandler) GetStatus(context.Context, *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netmon.v1.NetmonService.GetStatus is not implemented"))
}

func (UnimplementedNetmonServiceHandler) WatchStatus(context.Context, *connect.Request[v1.WatchStatusRequest], *connect.ServerStream[v1.WatchStatusResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("netmon.v1.NetmonService.WatchStatus is not implemented"))
}

func (UnimplementedNetmonServiceHandler) WatchTasks(context.Context, *connect.Request[v1.WatchTasksRequest], *connect.ServerStream[v1.WatchTasksResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("netmon.v1.NetmonService.WatchTasks is not implemented"))
}

func (UnimplementedNetmonServiceHandler) Trace(context.Context, *connect.Request[v1.TraceRequest], *connect.ServerStream[v1.TraceResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("netmon.v1.NetmonService.Trace is not implemented"))
}

func (UnimplementedNetmonServiceHandler) GetState(context.Context, *connect.Request[v1.GetStateRequest]) (*connect.Response[v1.GetStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netmon.v1.NetmonService.GetState is not implemented"))
}

func (UnimplementedNetmonServiceHandler) GetInfo(context.Context, *connect.Request[v1.GetInfoRequest]) (*connect.Response[v1.GetInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netmon.v1.NetmonService.GetInfo is not implemented"))
}

func (UnimplementedNetmonServiceHandler) GetStats(context.Context, *connect.Request[v1.GetStatsRequest]) (*connect.Response[v1.GetStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netmon.v1.NetmonService.GetStats is not implemented"))
}

func (UnimplementedNetmonServiceHandler) Refresh(context.Context, *connect.Request[v1.RefreshRequest]) (*connect.Response[v1.RefreshResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netmon.v1.NetmonService.Refresh is not implemented"))
}

func (UnimplementedNetmonServiceHandler) SetDebug(context.Context, *connect.Request[v1.SetDebugRequest]) (*connect.Response[v1.SetDebugResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netmon.v1.NetmonService.SetDebug is not implemented"))
}

func (UnimplementedNetmonServiceHandler) SetRuntimeStatsInterval(context.Context, *connect.Request[v1.SetRuntimeStatsIntervalRequest]) (*connect.Response[v1.SetRuntimeStatsIntervalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("netmon.v1.NetmonService.SetRuntimeStatsInterval is not implemented"))
}
